spring:
  redis:
    database: 0
    host: 192.168.0.118
    port: 6379
    password: 123456
    timeout: 10000
    lettuce:
      pool:
        max-active: 128 #最大活跃链接数 默认8
        max-wait: -1 #最大等待时间（使用负值表示没有限制）
        max-idle: 64 # 最大空闲连接数 默认8
        min-idle: 32 #最小空闲连接数 默认0
      shutdown-timeout: 100 # 关闭超时时间
